
SRC_FILE:= main.c sad_cpu.c sad_openmp.c

EXE_FILE:= sad
EXE_FILE_MP:= sad_mp

INPUT_PIC_LEFT:=001_im0.raw
INPUT_PIC_RIGHT:=001_im1.raw
OUTPUT_DEPTH_MAP:=001_im_depth_0.raw
PIC_SIZE_WIDTH:=2872
PIC_SIZE_HEIGHT:=1984
DISPARITY_LENGHT:=64

INCLUDE_LIBRARY:= 

OPTION_FLAG:= -Wall
OPENMP_OPTION:= -fopenmp
OPENMP_FLAG := _SAD_OPENMP_
OPENMP_THREADS_NUM_FLAG := OMP_NUM_THREADS
BUILD:= gcc
BUILD_MP:= gcc-6

all:
	$(BUILD) -o $(EXE_FILE) $(SRC_FILE) $(INCLUDE_LIBRARY) $(OPTION_FLAG)
	$(BUILD_MP) -D $(OPENMP_FLAG) $(OPTION_FLAG) $(OPENMP_OPTION) -o $(EXE_FILE_MP) $(SRC_FILE) $(INCLUDE_LIBRARY) 

run:
	time ./$(EXE_FILE) $(INPUT_PIC_LEFT) $(INPUT_PIC_RIGHT) $(OUTPUT_DEPTH_MAP) $(PIC_SIZE_WIDTH) $(PIC_SIZE_HEIGHT) $(DISPARITY_LENGHT)

	export $(OPENMP_THREADS_NUM_FLAG)=2
	time ./$(EXE_FILE_MP) $(INPUT_PIC_LEFT) $(INPUT_PIC_RIGHT) $(OUTPUT_DEPTH_MAP) $(PIC_SIZE_WIDTH) $(PIC_SIZE_HEIGHT) $(DISPARITY_LENGHT)

	export $(OPENMP_THREADS_NUM_FLAG)=4
	time ./$(EXE_FILE_MP) $(INPUT_PIC_LEFT) $(INPUT_PIC_RIGHT) $(OUTPUT_DEPTH_MAP) $(PIC_SIZE_WIDTH) $(PIC_SIZE_HEIGHT) $(DISPARITY_LENGHT)

	export $(OPENMP_THREADS_NUM_FLAG)=6
	time ./$(EXE_FILE_MP) $(INPUT_PIC_LEFT) $(INPUT_PIC_RIGHT) $(OUTPUT_DEPTH_MAP) $(PIC_SIZE_WIDTH) $(PIC_SIZE_HEIGHT) $(DISPARITY_LENGHT)

	export $(OPENMP_THREADS_NUM_FLAG)=8
	time ./$(EXE_FILE_MP) $(INPUT_PIC_LEFT) $(INPUT_PIC_RIGHT) $(OUTPUT_DEPTH_MAP) $(PIC_SIZE_WIDTH) $(PIC_SIZE_HEIGHT) $(DISPARITY_LENGHT)


#allmp:
#	$(BUILD_MP) -o $(OPENMP_FLAG) $(EXE_FILE_MP) $(SRC_FILE) $(INCLUDE_LIBRARY) $(OPTION_FLAG)

